import Phaser from 'phaser'
import './style.css'
import { attack, createGame, endTurn, enemyTurn, GameState, HEIGHT, isWalkable, key, legalMoves, move, roomAt, selectUnit, systems, WIDTH } from './sim/game'

const CELL=58, OX=52, OY=78
let state=createGame()
class TacticalScene extends Phaser.Scene {
  private board!: Phaser.GameObjects.Container
  create(){ this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>this.click(p.x,p.y)); this.draw() }
  click(px:number,py:number){if(state.phase!=='player'||state.status!=='playing')return;const x=Math.floor((px-OX)/CELL),y=Math.floor((py-OY)/CELL);if(!isWalkable({x,y}))return;const unit=state.units.find(u=>u.hp>0&&u.x===x&&u.y===y);if(unit?.team==='crew')state=selectUnit(state,unit.id);else if(unit?.team==='enemy')state=attack(state,unit.id);else state=move(state,x,y);this.draw()}
  draw(){this.children.removeAll();const g=this.add.graphics();g.fillStyle(0x07101c,1).fillRect(0,0,800,600);for(let y=0;y<HEIGHT;y++)for(let x=0;x<WIDTH;x++){const p={x,y},walk=isWalkable(p);g.fillStyle(walk?(roomAt(p)==='Boarding Bay'?0x132b38:roomAt(p)==='Medbay'?0x173437:roomAt(p)==='Reactor'?0x302538:roomAt(p)==='Bridge'?0x192c45:0x302c27):0x03070c,1).fillRect(OX+x*CELL,OY+y*CELL,CELL-2,CELL-2);if(walk)g.lineStyle(1,0x426277,.45).strokeRect(OX+x*CELL,OY+y*CELL,CELL-2,CELL-2)}
  // bulkheads and open door passages
  g.lineStyle(5,0x7890a0,1);g.lineBetween(OX+4*CELL,OY,OX+4*CELL,OY+3*CELL);g.lineBetween(OX+4*CELL,OY+4*CELL,OX+4*CELL,OY+8*CELL);g.lineBetween(OX+8*CELL,OY,OX+8*CELL,OY+4*CELL);g.lineBetween(OX+8*CELL,OY+5*CELL,OX+8*CELL,OY+8*CELL)
  const selected=state.units.find(u=>u.id===state.selectedId);for(const p of legalMoves(state)){g.fillStyle(0x55d9d0,.24).fillRect(OX+p.x*CELL+4,OY+p.y*CELL+4,CELL-10,CELL-10)}
  for(const s of systems){g.fillStyle(0xf1bd5b,.55).fillRoundedRect(OX+s.x*CELL+12,OY+s.y*CELL+12,32,32,5);this.add.text(OX+s.x*CELL+15,OY+s.y*CELL+22,s.system!,{fontFamily:'monospace',fontSize:'10px',color:'#08121c'})}
  for(const u of state.units.filter(u=>u.hp>0)){const cx=OX+u.x*CELL+28,cy=OY+u.y*CELL+28;if(u.id===state.selectedId)g.lineStyle(3,0xffffff,1).strokeCircle(cx,cy,22);g.fillStyle(u.team==='crew'?0x5de0d2:0xff5c68,1).fillCircle(cx,cy,17);this.add.text(cx,cy,u.name.split(' ')[0][0],{fontFamily:'monospace',fontSize:'17px',fontStyle:'bold',color:'#061019'}).setOrigin(.5);g.fillStyle(0x04070b,1).fillRect(cx-21,cy+20,42,5);g.fillStyle(u.team==='crew'?0x5de0d2:0xff5c68,1).fillRect(cx-21,cy+20,42*u.hp/u.maxHp,5)}
  const labels=[['BOARDING BAY',1,7],['MEDBAY',5,0],['REACTOR',5,7],['BRIDGE',9,0],['WEAPONS',9,7]] as const;labels.forEach(([t,x,y])=>this.add.text(OX+x*CELL,OY+y*CELL+(y?35:8),t,{fontFamily:'monospace',fontSize:'11px',color:'#91a9b8'}));this.add.text(52,28,`TURN ${String(state.turn).padStart(2,'0')}  //  ${state.phase.toUpperCase()} PHASE`,{fontFamily:'monospace',fontSize:'18px',color:state.phase==='player'?'#63e3d6':'#ff6670'});if(state.status!=='playing'){g.fillStyle(0x02060b,.86).fillRect(0,0,800,600);this.add.text(400,260,state.status==='victory'?'SHIP SECURED':'BOARDING TEAM LOST',{fontFamily:'monospace',fontSize:'32px',fontStyle:'bold',color:state.status==='victory'?'#63e3d6':'#ff6670'}).setOrigin(.5);this.add.text(400,305,'Press RESTART to run the breach again.',{fontFamily:'monospace',fontSize:'15px',color:'#c7d6df'}).setOrigin(.5)} updateHud(state,selected)}
}
function updateHud(s:GameState,selected= s.units.find(u=>u.id===s.selectedId)){const hud=document.querySelector('#hud')!;hud.innerHTML=`<div><p class="kicker">MISSION // ${s.status.toUpperCase()}</p><h2>${s.status==='playing'?'Eliminate all hostiles':s.status==='victory'?'Enemy ship secured':'All crew lost'}</h2><p>Turn ${s.turn} · ${s.phase} phase</p></div><section><h3>Selected</h3><p>${selected?`<strong>${selected.name}</strong><br>${selected.role} · ${selected.ap} AP · ${selected.hp}/${selected.maxHp} HP`:'Enemy activity…'}</p></section><section><h3>Crew manifest</h3>${s.units.filter(u=>u.team==='crew').map(u=>`<button class="unit ${u.hp<=0?'dead':''}" data-unit="${u.id}" ${u.hp<=0?'disabled':''}><span>${u.name}<small>${u.role}</small></span><b>${u.hp>0?`${u.hp} HP · ${u.ap} AP`:'KIA'}</b></button>`).join('')}</section><section><h3>Hostiles</h3>${s.units.filter(u=>u.team==='enemy').map(u=>`<p class="hostile"><span>${u.name}</span><b>${u.hp>0?`${u.hp}/${u.maxHp}`:'NEUTRALIZED'}</b></p>`).join('')}</section><ol class="log">${s.log.map(x=>`<li>${x}</li>`).join('')}</ol>`;hud.querySelectorAll<HTMLButtonElement>('[data-unit]').forEach(b=>b.onclick=()=>{state=selectUnit(state,b.dataset.unit!);scene.draw()})}
const scene=new TacticalScene('Tactical')
new Phaser.Game({type:Phaser.AUTO,parent:'phaser-game',width:800,height:600,backgroundColor:'#07101c',scene,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}})
document.querySelector<HTMLButtonElement>('#end-turn')!.onclick=()=>{state=endTurn(state);scene.draw();if(state.phase==='enemy')window.setTimeout(()=>{state=enemyTurn(state);scene.draw()},650)}
document.querySelector<HTMLButtonElement>('#restart')!.onclick=()=>{state=createGame();scene.draw()}
